[package]
name = "ipc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
rand = "0.9.0-alpha.2"
engine = { path = "../engine" }