[package]
name = "test_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
uuid = { version = "1.10.0", features = ["serde", "v4"] }
bincode = "1.3.3"
ipc = { path = "../ipc" }
